## 00. PyTorch Fundamentals

In [ ]:
import torch
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to Tensors

### Creating tensors

Make tensors using `torch.Tensor()`

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#dimensions
scalar.ndim

0

In [ ]:
#get scalar tensor back as python int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
#Bilal's Tensor

In [ ]:
bilalTensor = torch.tensor([[[3,3,3],
                             [5,5,5]]])

In [ ]:
bilalTensor.ndim

3

In [ ]:
bilalTensor.shape

torch.Size([1, 2, 3])

### Random Tensors

Why random tensors? You should start with Random tensors and then adjust those to better represent the data.

`Start with random numbers -> Look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
#Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0528, 0.8571, 0.8446, 0.5835],
        [0.1320, 0.8178, 0.1659, 0.2388],
        [0.1614, 0.0238, 0.9092, 0.5670]])

In [ ]:
#random tensor with similar shape to image tensor
randomImageSizeTensor = torch.rand(size=(224,224,3))
randomImageSizeTensor.shape, randomImageSizeTensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zero's and Ones Tensor

In [ ]:
#create a tensor of all zeros
zero = torch.zeros(size=(3,5,2))
zero

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors like

In [ ]:
# Use torch.range()
oneToTen = torch.arange(0,10)
oneToTen

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# creating tensors like
tenZeros = torch.zeros_like(input=oneToTen)
tenZeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#bilals range and tensor like
oneToWhatever = torch.arange(start=5,end=1220, step=94)
oneToWhatever

someZeros = torch.zeros_like(oneToWhatever)
someZeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into.

1. Not right datatype
2. Not right shape
3. Not on the right device

In [ ]:
# Float 32 tensor
float32Tensor = torch.tensor([3.0,6.0,9.0],
                             dtype=None, #what datatype is the tensor, eg float16, float32
                             device=None, #None, cpu, cuda, etc. They need to be on the same device
                             requires_grad=False) #if you want to track the gradient
float32Tensor

tensor([3., 6., 9.])

In [ ]:
float32Tensor.dtype

torch.float32

In [ ]:
float16Tensor = float32Tensor.type(torch.float16)
float16Tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
(float16Tensor * float32Tensor).dtype

torch.float32

In [ ]:
int32Tensor = torch.tensor([3,6,9],
                           dtype=torch.int32)
int32Tensor

tensor([3, 6, 9], dtype=torch.int32)

## Getting information from Tensors
1. Tensors not right datatype - `tensor.dtype`
2. Tensors not right shape - `tensor.shape`
3. Tensors not on the right device - `tensor.device`



In [ ]:
someTensor = torch.rand(3,4)
someTensor

tensor([[0.6925, 0.3999, 0.2783, 0.0232],
        [0.3750, 0.4844, 0.1370, 0.5832],
        [0.9462, 0.2729, 0.8593, 0.0128]])

In [ ]:
print(someTensor)
print(f"Datatype of tensor: {someTensor.dtype}")
print(f"Shape of Tensor: {someTensor.shape}")
print(f"Device of Tensor: {someTensor.device}")

tensor([[0.6925, 0.3999, 0.2783, 0.0232],
        [0.3750, 0.4844, 0.1370, 0.5832],
        [0.9462, 0.2729, 0.8593, 0.0128]])
Datatype of tensor: torch.float32
Shape of Tensor: torch.Size([3, 4])
Device of Tensor: cpu


In [ ]:
someTensorNewDevice = someTensor.to(torch.device('cpu'))

## Manipulating Tensors (tensor operations)

Operations include:
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix multiplicaton


In [ ]:
# Create a tensor and add to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#Multiply
tensor * 10

tensor([10, 20, 30])

In [ ]:
#subtract
tensor - 10

tensor([-9, -8, -7])

In [ ]:
#PyTorch
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

## Matrix Multiplication
1. Element-wise multiplication
2. Matrix Multiplication (dot product)



In [ ]:
print(tensor, "*", tensor)
print(f"Equals: {tensor *tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.19 ms, sys: 196 µs, total: 2.39 ms
Wall time: 3.8 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.32 ms, sys: 0 ns, total: 1.32 ms
Wall time: 2.16 ms


tensor(14)

### Matrix Multiplication
1. Element-wise multiplication
2. Matrix multiplication (dot product)

1. The **inner dimensions** must match:
(3,2) @ (2,3)
(a,b) @ (c,d) -> final is a x d where b,c is same.


In [ ]:
torch.matmul(torch.rand(size=(3,2)), torch.rand(size=(2,3)))

tensor([[0.3689, 0.0427, 0.0354],
        [0.5467, 0.0627, 0.0517],
        [1.0785, 0.3551, 0.4465]])

## One of the most common errors: Shape Errors!

In [ ]:
#Shapes for Matrix Multiplication
tensorA = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
                        #3x2

tensorB = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
                        #3x2
#3x2 by 3x2 not allowed
# torch.matmul(tensorA,tensorB)

In [ ]:
tensorB

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensorB.T, tensorB.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.matmul(tensorA,tensorB.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)


In [ ]:
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
#Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
%%time
torch.sum(x.type((torch.float32)))

CPU times: user 201 µs, sys: 32 µs, total: 233 µs
Wall time: 242 µs


tensor(460.)

In [ ]:
%%time
x.sum()

#exact same time?

CPU times: user 141 µs, sys: 22 µs, total: 163 µs
Wall time: 173 µs


tensor(460)

## Finding the positional min and max

In [ ]:
#find the position in tensor that has the minimum value (returns the index)
x,x.argmin()

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), tensor(0))

In [ ]:
#find the position that has the maximum value with argmax()
x,x.argmin()

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), tensor(0))

## Reshaping, stacking, squeezing, and unsqueezing Tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
import torch
x = torch.arange(1,10,1)
x.shape,x

(torch.Size([9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
#add an extra dimension
xReshaped = x.reshape(1,9)
xReshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# Change the view
z = x.view(1,9)
z,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# z is a shallow copy of x and they reference the same tensor
z[:,0] = 5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# Stack tensors atop of one another
xStacked = torch.stack([x,x,x,x], dim=0)
xStacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
xReshaped.shape


torch.Size([1, 9])

In [ ]:
#removes all single dimensions from target
y = torch.squeeze(xReshaped)
y

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#adds a single dimension to target
print(f"Previous target: {y}")
print(f"Previous shape: {y.shape}")

yUnsqueezed = y.unsqueeze(dim=0)
print(f"New target: {yUnsqueezed}")
print(f"New shape: {yUnsqueezed.shape}")


Previous target: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])
New target: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [ ]:
#torch.permute - rearranges the dimensions of a target tensor in specified order
xOriginal = torch.rand(size=(224,224,3))
xOriginal.shape

torch.Size([224, 224, 3])

In [ ]:
xPermuted = xOriginal.permute(2,1,0)
xPermuted.shape

print(f"Original shape: {xOriginal.shape}")
print(f"New shape: {xPermuted.shape}")

Original shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
xOriginal[0,0,0] = 1

In [ ]:
xPermuted

tensor([[[1.0000, 0.7289, 0.7277,  ..., 0.7909, 0.2767, 0.9517],
         [0.2048, 0.6429, 0.5156,  ..., 0.2891, 0.8699, 0.9807],
         [0.9752, 0.1190, 0.6287,  ..., 0.5050, 0.8021, 0.0617],
         ...,
         [0.1076, 0.4368, 0.9882,  ..., 0.0757, 0.1791, 0.4543],
         [0.3537, 0.2484, 0.8363,  ..., 0.2348, 0.4098, 0.9823],
         [0.9952, 0.4844, 0.0143,  ..., 0.9816, 0.7842, 0.0088]],

        [[0.5519, 0.8673, 0.9520,  ..., 0.9700, 0.0067, 0.7295],
         [0.8948, 0.3122, 0.2282,  ..., 0.7615, 0.8479, 0.2204],
         [0.5830, 0.0578, 0.5917,  ..., 0.2204, 0.8371, 0.8574],
         ...,
         [0.6983, 0.4416, 0.9601,  ..., 0.5552, 0.9209, 0.5866],
         [0.4813, 0.3755, 0.8269,  ..., 0.6185, 0.9184, 0.9209],
         [0.4038, 0.7430, 0.4154,  ..., 0.0354, 0.8933, 0.8614]],

        [[0.9504, 0.5238, 0.1171,  ..., 0.8396, 0.9373, 0.5706],
         [0.7583, 0.6112, 0.4195,  ..., 0.4065, 0.4903, 0.4780],
         [0.9343, 0.9150, 0.6357,  ..., 0.9603, 0.7492, 0.

## Indexing (selecting data from tensors)
##### Indexing with PyTorch is similar to indexing with Numpy

In [ ]:
#create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0][1]

tensor([4, 5, 6])

In [ ]:
#how to get 9?
x[0][2][2]

tensor(9)

In [ ]:
#you can use : to select all from target dimension ie
x[0][1][1]

tensor(5)

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# get all the values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[0,1,1]

tensor(5)

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
#index on x to return 9
x[0,2,2]

tensor(9)

In [ ]:
#return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch Tensors & Numpy
* Data in Numpy, want in PyTorch Tensor -> `torch.from_numpy(ndarray)
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

torch default is float32, np is float64

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0,8.0).dtype

torch.float32

In [ ]:
# change the value of array, what will this do to `tensor`?
array = array + 1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpyTensor = tensor.numpy()
tensor,numpyTensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor+1
tensor, numpyTensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take random out of random)

`start with random numbers -> tensor operations -> update random numbers to try making better operations`

introduce idea of random seed.

In [ ]:
import torch
randomTensorA = torch.rand(3,4)
randomTensorB = torch.rand(3,4)

print(randomTensorA)
print(randomTensorB)
print(randomTensorA == randomTensorB)

tensor([[0.7507, 0.0480, 0.1276, 0.0281],
        [0.8700, 0.6391, 0.8646, 0.7579],
        [0.2544, 0.9416, 0.2757, 0.1199]])
tensor([[0.8135, 0.6827, 0.5710, 0.8508],
        [0.2529, 0.9477, 0.1371, 0.1951],
        [0.9335, 0.6857, 0.7255, 0.4354]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

randomTensorC = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
randomTensorD = torch.rand(3,4)

print(randomTensorC)
print(randomTensorD)
print(randomTensorC == randomTensorD)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensors and PyTorch Ojbects on the GPU (and making faster computation)

### 1. Getting a GPU

1. Just use Colab
2. Set it up locally.
3. Use cloud computing - GCP, AWS, Azure

In [ ]:
!nvidia-smi

Fri Jan 24 22:10:56 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyToch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic Code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count Number of Devices
torch.cuda.device_count()

1

## 3. Putting tensors and Models on the GPU

Using a GPU means faster computations

In [ ]:
#create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], device='cpu')
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Move tensor to gpu (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

###4 . Moving Tensors back to the CPU


In [ ]:
#if the tensor is on the gpu, we can't transform it to Numpy
tensor_on_cpu = tensor_on_gpu.to('cpu').numpy()
tensor_on_cpu

array([1, 2, 3])

# Exercises

In [ ]:
#2 Create a random tensor with shape (7,7)
import torch
randomTensor = torch.rand(7,7)
randomTensor

tensor([[0.7903, 0.0152, 0.3598, 0.7220, 0.3671, 0.4422, 0.2782],
        [0.8254, 0.9797, 0.3027, 0.7447, 0.1440, 0.7986, 0.9821],
        [0.5601, 0.0029, 0.8231, 0.8790, 0.0166, 0.5731, 0.6121],
        [0.4187, 0.0614, 0.6229, 0.0232, 0.5755, 0.4900, 0.1539],
        [0.6914, 0.0609, 0.5321, 0.0290, 0.7666, 0.0764, 0.9458],
        [0.6142, 0.6342, 0.2491, 0.4733, 0.9064, 0.0728, 0.1932],
        [0.5186, 0.8965, 0.8892, 0.0407, 0.9715, 0.2886, 0.3221]])

In [ ]:
#3 Perform matrix multiplication on the tensor from 2 with another random tensor with shape (1,7)
randomTensor2 = torch.rand(1,7)
#(7x7) by (1,7) is not allowed -> transpose
randomTensor2Transpose = torch.transpose(randomTensor2,0,1)
randomTensor2Transpose.shape

matrixMulTensor = torch.matmul(randomTensor, randomTensor2Transpose)
matrixMulTensor



tensor([[1.2510],
        [2.7459],
        [1.6656],
        [0.9807],
        [1.3090],
        [1.2402],
        [1.6690]])

In [ ]:
#4 Set the random seed to 0
torch.manual_seed(0)
randomTensorRandomSeed = torch.rand(7,7)

torch.manual_seed(0)
randomTensor2RandomSeedTranspose = torch.rand(1,7).T

matrixMulTensorQues3 = torch.matmul(randomTensorRandomSeed,randomTensor2RandomSeedTranspose)

In [ ]:
#5 Torch Manual Seed for GPU
torch.cuda.manual_seed(1234)

In [ ]:
#6 Create two random tensors of shape (2,3) and send to gpu & set manual seed t o1234
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.manual_seed(1234)
randomTensor6_1 = torch.rand((2,3),device=device)

torch.manual_seed(1234)
randomTensor6_2 = torch.rand((2,3), device=device)



In [ ]:
#7 Perform a matrix multiplication on the new tensors
# 2x3 by 2 x 3 not allowed -> transpose
matrixMulTensorQues7 = torch.matmul(randomTensor6_1, randomTensor6_2.T)
matrixMulTensorQues7

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')

In [ ]:
#8 Find the maximum and minimum values of the output of 7
minimumValue = torch.min(matrixMulTensorQues7)


maximumValue = torch.max(matrixMulTensorQues7)
minimumValue, maximumValue

(tensor(0.8358, device='cuda:0'), tensor(1.4578, device='cuda:0'))

In [ ]:
#9 Find the maximum and minimum index values of the output of 7
minimumValueLocation = torch.argmin(matrixMulTensorQues7)
maximumValueLocation = torch.argmax(matrixMulTensorQues7)

minimumValueLocation, maximumValueLocation

(tensor(1, device='cuda:0'), tensor(3, device='cuda:0'))